### ISSUE TITLE
StackOverflowException on simple model

### ISSUE THREAD

**Issue by LeonidEfremov** [GregFinzer/Compare-Net-Objects#140]
Got `System.StackOverflowException` when try to compare
```csharp
var expected = SuccessModel.Default;
var actual = ...

var compareLogic = new CompareLogic();
var result = compareLogic.Compare(expected, actual);
```
this model
```csharp
/// <summary>Success model.</summary>
[DataContract]
public class SuccessModel
{
    /// <summary>Get or Set Success status.</summary>
    [DataMember]
    public bool Success { get; set; }

    /// <summary> Default state for Success model.</summary>
    public static SuccessModel Default => new SuccessModel { Success = true };
}
```

**Comment by GregFinzer** [comment]
Yep, that is a defect.  Thanks for posting.

**Comment by GregFinzer** [comment]
@LeonidEfremov I was thinking last night that this is a defect that cannot be fixed since it will always create a new Default during the comparison.  To get around this issue, simply ignore that member.

CompareLogic compare = new CompareLogic();
compare.Config.MembersToIgnore.Add("SuccessModel.Default");

Thanks,
Greg
