### ISSUE TITLE
Bug when comparing ordering of Dictionary<>

### ISSUE THREAD

**Issue by SteveDunn** [GregFinzer/Compare-Net-Objects#164]
I need to compare two `Dictionary` objects that have a non-primitive key.

Here's a unit test.  It fails, but I think it should pass:

```
    public class CompareLogicSpecs
    {
        [Scenario]
        public void Plain_dictionary_ordering_with_a_complex_key(
            Dictionary<ComplexKey, string> left,
            Dictionary<ComplexKey, string> right,
            CompareLogic compareLogic,
            ComparisonResult result)
        {
            "Given two objects where the only differences are the ordering of the dictionary".x(() =>
            {
                left = new Dictionary<ComplexKey, string>
                {
                    {new ComplexKey {Name = "Old", Age = 100}, "aaa"},
                    {new ComplexKey {Name = "Young", Age = 10}, "aaa"}
                };

                right = new Dictionary<ComplexKey, string>
                {
                    {new ComplexKey {Name = "Young", Age = 10}, "aaa"},
                    {new ComplexKey {Name = "Old", Age = 100}, "aaa"},
                };

                compareLogic = new CompareLogic
                {
                    Config =
                    {
                        IgnoreCollectionOrder = true
                    }
                };
            });

            "When we compare them".x(() => result = compareLogic.Compare(left, right));

            "Then there should be no differences".x(() => result.Differences.Should().BeEmpty());
        }

        public class ComplexKey
        {
            public string Name { get; set; }
            public int Age { get; set; }
        }
    }

```

If I change `aaa` to something else, it works, e.g. with this data, the test passes:
```
                left = new Dictionary<ComplexKey, string>
                {
                    {new ComplexKey {Name = "Old", Age = 100}, "old!!"},
                    {new ComplexKey {Name = "Young", Age = 10}, "aaa"}
                };

                right = new Dictionary<ComplexKey, string>
                {
                    {new ComplexKey {Name = "Young", Age = 10}, "aaa"},
                    {new ComplexKey {Name = "Old", Age = 100}, "old!!"},
                };
```

Is this really a bug? - I've been looking at a problem for hours (so I might be missing something obvious) and have boiled it down to this reproducible example.

**Comment by SteveDunn** [comment]
The `Difference` is:
`{Types [String,String], Item Expected[[TestHarness.Glg.TradeData.DiscoveryTests.CompareLogicSpecs+ComplexKey, old!!]].Key.Name != Actual[[TestHarness.Glg.TradeData.DiscoveryTests.CompareLogicSpecs+ComplexKey, old!!]].Key.Name, Values (Old,Young)}`

**Comment by GregFinzer** [comment]
@SteveDunn Compare .NET Objects does not support non primitive keys for dictionaries.  This would be a new feature.  Would you like to implement it?

**Comment by SteveDunn** [comment]
> @SteveDunn Compare .NET Objects does not support non primitive keys for dictionaries. This would be a new feature. Would you like to implement it?

Hi @GregFinzer - sure, I'll take a look, happy to help where I can!

**Comment by GregFinzer** [comment]
@SteveDunn How is this enhancement going? @jsobell wants to do a release soon

**Comment by SteveDunn** [comment]
Hi Greg, sorry, haven't had a moment free. It's on my list though as I do
like to contribute back to useful projects!

**Comment by jsobell** [comment]
I had a quick look at this, and immediately hit the issue that any non-primitive brings us back into a recursive serialisation situation because we have no idea how deep the key might go. GetHash isn't a valid option because it usually isn't be implemented by user objects.
Do we include a custom string serialiser, or allow an extensible `CreateKey` function in the config to allow hooking in a custom hash generator or even a raw Json serialiser? At least that way people have the flexibility to implement smarts to avoid hash clashes if it's likely to be an issue.
I'm just wary of adding a dependency on something like NewtonSoft, but if it's a choice of that or creating yet-another-serialisation-lib from scratch...

**Comment by GregFinzer** [comment]
@jsobell This is the first time that I have seen something other than a primitive type used as a key in a dictionary.  I did not know something like this was possible.   Is there an enumerator for complex keys like this?

**Comment by jsobell** [comment]
Honestly, they're not particularly useful in most cases. Any object can be used as a key, but the comparisons are done as objects, not their internal data properties, so unless you retain a reference to the original content you can't find the items again, so they are of limited use in practice:
```c#
void Main()
{
	Dictionary<KeyThing, string> dict = new Dictionary<UserQuery.KeyThing, string>();
	var key1 = new KeyThing { Age = 1, Name = "Baby" };
	var key2 = new KeyThing { Age = 2, Name = "Toddler" };
	dict.Add(key1, "First Entry");
	dict.Add(key2, "Second Entry");

	dict.ContainsKey(new KeyThing { Age = 2, Name = "Toddler" }).Dump();
	// False
	dict.ContainsKey(key2).Dump();
	// True
}

public class KeyThing
{
	public int Age { get; set; }
	public string Name { get; set; }
}
```
But, if people have these then they need comparing, so the only practical way is to serialise them to ensure all the child contents match. It's not feasible to use the existing comparison code because we can't exclude types, change case, or any other modification of the key values as they have to match 100%.
Instance counting becomes important too, because we could have the same values in two keys as two instances in a Dictionary (key2a and key2b have identical property values):
```c#
void Main()
{
	Dictionary<KeyThing, string> dict = new Dictionary<UserQuery.KeyThing, string>();
	var key1 = new KeyThing { Age = 1, Name = "Baby" };
	var key2a = new KeyThing { Age = 2, Name = "Toddler" };
	var key2b = new KeyThing { Age = 2, Name = "Toddler" };
	dict.Add(key1, "First Entry");
	dict.Add(key2a, "Second Entry A");
	dict.Add(key2b, "Second Entry B");

	dict.ContainsKey(new KeyThing { Age = 2, Name = "Toddler" }).Dump();
	// Always fails
	dict[key2a].Dump();
	// Returns "Second Entry A"
	dict[key2b].Dump();
	// Returns "Second Entry B"
}

public class KeyThing
{
	public int Age { get; set; }
	public string Name { get; set; }
}
```

Yes, the compound keys might as well be a memory pointer to the object, as it's the instance being used as a key, but we can't compare these as they will presumably be from different instances.

**Comment by GregFinzer** [comment]
@SteveDunn Hey there was a nice PR by @Krizzzn that may help with the issue above.  Can you do a get latest on the source and try it?

Here is the PR:  https://github.com/GregFinzer/Compare-Net-Objects/pull/174

**Comment by jsobell** [comment]
I had a quick look at that PR, and from what I see it's doing a `.ToString()` on the key, so this won't work.
In @SteveDunn 's original example all of the keys will be `[UserQuery+ComplexKey, aaa]`, because the class string definition will be (by default) the name of the type.
The only way the PR code will find a match is if the `ComplexKey` class has a string override to return it's data in string format:
```
public class ComplexKey
{
	public string Name { get; set; }
	public int Age { get; set; }
	public override string ToString() { return $"{Name},{Age}";	}
}
```

As I mentioned earlier, unless we serialize the complex objects to create keys we can't compare from two sources as they have to be the same instances of objects to match:
```
(new ComplexKey {Name = "Me!", Age = 99} == new ComplexKey {Name = "Me!", Age = 99})
// Returns false
```

**Comment by GregFinzer** [comment]
Closing inactive issue.
