### ISSUE TITLE
System.StackOverflowException

### ISSUE THREAD

**Issue by jenssc** [GregFinzer/Compare-Net-Objects#175]
Hi
I've just updated to the latest version of CompareNETObjects from version v4.59.0 and now I'm getting a System.StackOverflowException whenever I try to do any kind of list operations like IndexOf!

I've manage to create a very simple xUnitTest file that demonstrates the problem. If you compile the test with v4.59.0 it is working but with v4.63.0 you will get an exception.

[UnitTest1.cs.txt](https://github.com/GregFinzer/Compare-Net-Objects/files/3657257/UnitTest1.cs.txt)

What am I missing?

Best regards,
Jens Christiansen

**Comment by GregFinzer** [comment]
Jens,

Beginning with 4.62 and higher the .NET Compare Objects library no longer uses the HashCode to determine if it is the same object but the reference equals.  Because you have overridden Equals to something other than Reference Equals that is why you are getting the stack overflow exception.  You will need to rewrite your code to account for this or use version 4.59.
