### ISSUE TITLE
ComparePrivateProperties missing in ComparisonConfig

### ISSUE THREAD

**Issue by dradovic** [GregFinzer/Compare-Net-Objects#77]
I'm upgrading to 3.6.0 and I've got a compilation error that the `ComparePrivateProperties` property is missing on the `ComparisonConfig` class.

What is the replacement for this functionality? I haven't found anything in the release notes.

**Comment by GregFinzer** [comment]
From the home page:

"The Portable and .NET Standard builds cannot compare private fields or properties on a class. This is a security restriction by Microsoft."

**Comment by dradovic** [comment]
Thanks! And thank you for sharing this library with the world that has already served me many years.

**Comment by GregFinzer** [comment]
@dradovic Thanks for the kind words.  Enjoy the software.

**Comment by ProductiveRage** [comment]
Is this still correct? I know that .NET Standard has been moving quickly and so things might have changed!

I know that from a .NET Standard 2.0 library that it is possible to read private fields from a class instance but perhaps it wasn't in Portable builds (if these are still required) and so there may be a limitation in this library, somehow, rather than it being a .NET Standard security issue?

Also, I couldn't see the text "The Portable and .NET Standard builds cannot compare private fields or properties on a class. This is a security restriction by Microsoft" on  the GitHub home page for this repo (https://github.com/GregFinzer/Compare-Net-Objects), am I looking in the right place?

**Comment by GregFinzer** [comment]
I created a test and altered the code so that .NET Standard can compare private properties and fields.  Can you test?
https://github.com/GregFinzer/Compare-Net-Objects/commit/e752b75b0a9b72075aa341eaf1d2929286c796a4
[https://avatars3.githubusercontent.com/u/16633931?s=200&v=4]<https://github.com/GregFinzer/Compare-Net-Objects/commit/e752b75b0a9b72075aa341eaf1d2929286c796a4>

Allow .NET Standard to compare private properties and fields · GregFinzer/Compare-Net-Objects@e752b75<https://github.com/GregFinzer/Compare-Net-Objects/commit/e752b75b0a9b72075aa341eaf1d2929286c796a4>
What you have been waiting for :+1: Perform a deep compare of any two .NET objects using reflection. Shows the differences between the two objects. - GregFinzer/Compare-Net-Objects
github.com



Thanks,
Greg


________________________________

**Comment by ProductiveRage** [comment]
Thanks for getting back to me so quickly. I cloned the repo to try it out and it all built and the tests ran and a NuGet package was created - that's a great start, thumbs up for making it so easy for someone to get started! :)

I had a look at the code and I wrote a unit test myself, which passed when I ran it in the VS Test Runner:

```
[Test]
public void DanTest1()
{
	var x = new SomethingWithPrivateField(123);
	var y = new SomethingWithPrivateField(456);
	var c = new CompareLogic(new ComparisonConfig
	{
		ComparePrivateFields = true,
		ComparePrivateProperties = true
	});
	var r = c.Compare(x, y);
	Assert.IsFalse(r.AreEqual);
}

private class SomethingWithPrivateField
{
	private readonly int _key;
	public SomethingWithPrivateField(int key) { _key = key; }
}
```

(Don't worry about the rubbish name, I haven't pushed it, I just wanted to try the code myself)

However.. when I tried to use it in a .NET Core 2.0 console app, it _didn't_ work correctly.

Then I remembered that the VS Test Runner doesn't run tests in all target frameworks, for cases where multiple frameworks are specified. So I ran `dotnet test` from the command line instead and then I saw the test fail (the comparer says that the two objects are equal when they're not).

**Comment by ProductiveRage** [comment]
@GregFinzer, it looks like the code you changed altered how properties are enumerated for .NET Standard but not fields? I've made some changes to try to address this (and tidied up my unit test so that there is coverage).

The access of ".BaseType" required by the field-enumerating code is not supported in .NET Standard 1.3 and so I removed the two config options "ComparePrivateFields" and "ComparePrivateProperties" entirely for .NET Standard 1.3 builds, while leaving them in for other frameworks.

Pushed in https://github.com/GregFinzer/Compare-Net-Objects/pull/119

Jumping into the code and trying to find what needed changing seemed quite straight forward - thanks again, it's always nice to encounter an approachable code base!

**Comment by GregFinzer** [comment]
Thanks so much!  Merged.


Greg


________________________________

**Comment by GregFinzer** [comment]
@ProductiveRage By the way, re-sharper will run for all frameworks.  It works great for that.

**Comment by ProductiveRage** [comment]
@GregFinzer Interesting to know, thanks!

**Comment by ProductiveRage** [comment]
@GregFinzer Thanks for publishing a NuGet package with this fix in so quickly!

In case you were curious, I'm using it in a project I'm tinkering with -

https://github.com/ProductiveRage/DanSerialiser

When writing the unit tests for more complex types, I considered comparing all of the field and properties manually and then considered using reflection and *then* thought "there *must* be a better way" - and there is! Thanks again for all your work :)

**Comment by GregFinzer** [comment]
@ProductiveRage 

That is interesting.  I like the idea of versioning.  You spent a lot of time on performance.  I have not tested the performance of mine compared to the others.  

Have you seen this?  It is not a coincidence that Compare .NET Objects exists, the main reason why it was created was to test my serializer.  
  
https://github.com/GregFinzer/KellermanSoftware-Serialization

The serializer is used in this database that no-one cares about:
https://kellermansoftware.com/products/ninja-net-database-pro

**Comment by ProductiveRage** [comment]
@GregFinzer I hadn't realised that you'd written a serialiser too! :D *And* a database!

I spent some time on performance for a couple of reasons - to any interested third party, I wanted to try to ensure that it wasn't horrendously slow (though features come before performance in this case).. being at least as fast as Json.NET was what I really wanted. But I also have a use case for this where I work - we flush entity data out of memory and onto disk between service restarts because it's a lot cheaper to pull the data back off disk when it starts up (compared to trying to get it live from the db) but it can still take twenty minutes and things are running slowly during that time. The code to deserialise is currently all hand-written so that it can load that data back as quickly as possible but this can be error prone *and* if the entities change when a new version of the service is pushed out then the files are all invalid, in which case we need to pre-build those cache files and include them in the service update package. I want to use my serialiser so that we don't have to write that de/serialisation code by hand and to try to make it possible for cache files from the previous version of the service to be compatible with the updated version. If the serialiser was *much* slower then this whole plan would go nowhere!
